### PR TITLE
Added fr-latin9 layout

### PR DESCRIPTION
**Pull request by terrycain**
Added automatic keyboard layout recognition. That function needs a fair bit of work, ideally needs to be done is a better cross platform way but for now it'll do.

Added the fr-latin9 layout to the keyboard.

### CODE REVIEW

**Comment by terrycain** [comment]
@lah7 if you wouldn't mind testing. If you change your keyboard layout to "French (alternative Latin-9 only)" on ubuntu it should pick you the other keyboard layout.

**Comment by lah7** [comment]
Doesn't appear to launch after re-compiling, re-packaging, re-installing:

> Successfully connected to dbus service.
> Traceback (most recent call last):
  File "/tmp/razer_drivers-testing/gui/chroma_controller/chroma_controller.py", line 573, in <module>
    ChromaController()
  File "/tmp/razer_drivers-testing/gui/chroma_controller/chroma_controller.py", line 397, in __init__
    self.kb_layout = razer.keyboard.get_keyboard_layout()
AttributeError: 'module' object has no attribute 'get_keyboard_layout'

I tried to compile in a `i386` virtual machine (to avoid messing system settings), but discovered this project doesn't seem to compile.

**Comment by terrycain** [comment]
I just used the keyboard icon in the notification area to switch keyboard
layouts to test.

**Comment by lah7** [comment]
Cannot launch:
> Successfully connected to dbus service.
> Traceback (most recent call last):
>   File "/tmp/razer_drivers-testing/gui/chroma_controller/chroma_controller.py", line 573, in <module>
>     ChromaController()
>   File "/tmp/razer_drivers-testing/gui/chroma_controller/chroma_controller.py", line 397, in __init__
>     self.kb_layout = razer.keyboard.get_keyboard_layout()
>   File "/usr/lib/python3/dist-packages/razer/keyboard.py", line 337, in get_keyboard_layout
>     result = layout + '-' + variant
> TypeError: Can't convert 'NoneType' object to str implicitly

Also discovered this project doesn't compile in Ubuntu MATE 15.10 `i386` (virtual machine). I'll be using that, to avoid messing with system settings unnecessarily.

**Comment by terrycain** [comment]
What does `setxkbmap -query` output

**Comment by lah7** [comment]
> `rules:      evdev
> `model:      pc105`
> `layout:     gb`
> `options:    terminate:ctrl_alt_bksp`

**Comment by terrycain** [comment]
Fixed in 3ce7ebd
